### ISSUE TITLE
Error when downloading from annas archive

### ISSUE THREAD

**Issue by brycepg** [bbrown430/endless-library#4]
I'm guessing the structure of anna's archive changed

```Search for a book (type 'exit' to exit, 'back' to go back): we need to talk about kevin
Traceback (most recent call last):
  File "C:\Users\Bryce\endless-library\endless-library.py", line 15, in <module>
    Menu.book_search_menu()
  File "C:\Users\Bryce\endless-library\src\menu.py", line 60, in book_search_menu
    anna_list = anna_list.scrape(search_term)
  File "C:\Users\Bryce\endless-library\src\anna_list.py", line 49, in scrape
    books_html.pop()
IndexError: pop from empty list```

**Comment by brycepg** [comment]
Here's what the div's look like on my end:

```
<html>
<body>
<!--StartFragment-->
<div class="h-[110px] flex flex-col justify-center ">
--
  | <a href="/md5/5fb9a2b2b5d50726f06fcc51b6bc7cab" class="js-vim-focus h-[110px] custom-a flex items-center relative left-[-10px] w-[calc(100%+20px)] px-2.5 outline-offset-[-2px] outline-2 rounded-[3px] hover:bg-black/6.7 focus:outline ">
  | <div class="flex-none">
  | <div class="relative overflow-hidden w-[72px] h-[100px] flex flex-col justify-center">
  | <div class="absolute w-full h-[94px] js-img-background-573355ce280dc4e9b08418b494396eba" style="background-color: hsl(152deg 43% 73%)"></div>
  | <img class="relative inline-block" src="https://s3proxy.cdn-zlib.sk//covers299/collections/genesis/1cd3998277df63a336188544e14dafc344686df303c6fbc9927a177f6854bc48.jpg" alt="" referrerpolicy="no-referrer" onerror="this.parentNode.removeChild(this)" onload="for (let el of document.querySelectorAll('.js-img-background-573355ce280dc4e9b08418b494396eba')) { el.parentNode.removeChild(el); }" loading="lazy" decoding="async"/>
  | </div>
  | </div>
  | <div class="relative top-[-1] pl-4 grow overflow-hidden">
  | <div class="line-clamp-[2] leading-[1.2] text-[10px] lg:text-xs text-gray-500">English [en], .epub, 🚀/lgli/lgrs/nexusstc/zlib, 2.1MB, 📘 Book (non-fiction), nexusstc/House of Leaves/5fb9a2b2b5d50726f06fcc51b6bc7cab.epub</div>
  | <h3 class="max-lg:line-clamp-[2] lg:truncate leading-[1.2] lg:leading-[1.35] text-md lg:text-xl font-bold">House of Leaves</h3>
  | <div class="truncate leading-[1.2] lg:leading-[1.35] max-lg:text-xs">Pantheon, 2nd Edition, 2000</div>
  | <div class="max-lg:line-clamp-[2] lg:truncate leading-[1.2] lg:leading-[1.35] max-lg:text-sm italic">Mark Z. Danielewski</div>
  | <div class="hidden">base score: 11065.0, final score: 168044.81</div>
  | </div>
  | </a>
  | </div>

<!--EndFragment-->
</body>
</html><div class="h-[110px] flex flex-col justify-center ">
        <a href="[/md5/5fb9a2b2b5d50726f06fcc51b6bc7cab](https://annas-archive.org/md5/5fb9a2b2b5d50726f06fcc51b6bc7cab)" class="js-vim-focus h-[110px] custom-a flex items-center relative left-[-10px] w-[calc(100%+20px)] px-2.5 outline-offset-[-2px] outline-2 rounded-[3px] hover:bg-black/6.7 focus:outline ">
          <div class="flex-none">
            <div class="relative overflow-hidden w-[72px] h-[100px] flex flex-col justify-center">
              <div class="absolute w-full h-[94px] js-img-background-573355ce280dc4e9b08418b494396eba" style="background-color: hsl(152deg 43% 73%)"></div>
                <img class="relative inline-block" src="https://s3proxy.cdn-zlib.sk//covers299/collections/genesis/1cd3998277df63a336188544e14dafc344686df303c6fbc9927a177f6854bc48.jpg" alt="" referrerpolicy="no-referrer" onerror="this.parentNode.removeChild(this)" onload="for (let el of document.querySelectorAll('.js-img-background-573355ce280dc4e9b08418b494396eba')) { el.parentNode.removeChild(el); }" loading="lazy" decoding="async"/>
            </div>
          </div>
          <div class="relative top-[-1] pl-4 grow overflow-hidden">
            <div class="line-clamp-[2] leading-[1.2] text-[10px] lg:text-xs text-gray-500">English [en], .epub, 🚀/lgli/lgrs/nexusstc/zlib, 2.1MB, 📘 Book (non-fiction), nexusstc/House of Leaves/5fb9a2b2b5d50726f06fcc51b6bc7cab.epub</div>
            <h3 class="max-lg:line-clamp-[2] lg:truncate leading-[1.2] lg:leading-[1.35] text-md lg:text-xl font-bold">House of Leaves</h3>
            <div class="truncate leading-[1.2] lg:leading-[1.35] max-lg:text-xs">Pantheon, 2nd Edition, 2000</div>
            <div class="max-lg:line-clamp-[2] lg:truncate leading-[1.2] lg:leading-[1.35] max-lg:text-sm italic">Mark Z. Danielewski</div>
            <div class="hidden">base score: 11065.0, final score: 168044.81</div>
          </div>
        </a>
      </div>
      ```

**Comment by brycepg** [comment]
I fixed the html issue and now I'm getting

```
Traceback (most recent call last):
  File "C:\Users\Bryce\endless-library\endless-library.py", line 15, in <module>
    Menu.book_search_menu()
  File "C:\Users\Bryce\endless-library\src\menu.py", line 63, in book_search_menu
    searcher.interactive_search(anna_list)
  File "C:\Users\Bryce\endless-library\src\searcher.py", line 97, in interactive_search
    successful = io_utils.download_book(selected_book)
  File "C:\Users\Bryce\endless-library\src\io_utils.py", line 91, in download_book
    soup = self.cook_soup(url)
  File "C:\Users\Bryce\endless-library\src\io_utils.py", line 51, in cook_soup
    response = requests.get(url, headers=headers)
  File "C:\Users\Bryce\endless-library\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Bryce\endless-library\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Bryce\endless-library\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Bryce\endless-library\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Bryce\endless-library\venv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='library.lol', port=443): Max retries exceeded with url: /main/7a91237a3239b6eb9a7331545ccc5969 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CA93F57AC0>: Failed to resolve 'library.lol' ([Errno 11001] getaddrinfo failed)"))
```

**Comment by brycepg** [comment]
Looks like library.lol is down

**Comment by bbrown430** [comment]
#5 fixes, closed
